url: "https://sphaneufassociates.com"
name: "S. Phaneuf & Associates"
defaultDescription: "Professional paving, asphalt, masonry, and site development services in Massachusetts."
defaultOgImage: "S-Phaneuf-Associates.webp"
themeColor: "#303f5e"